-- Migration 034: FCN responsibility moved from FinanceHead -> DirectorOfAdministration.
-- Frozen business rule: FCN is generated by the Director of Administration.
-- Finance Head owns Finance Approval + Cheque only.

-- Grant FCN permissions to Director of Administration
INSERT INTO "RolePermission" ("RoleID", "PermissionID")
SELECT r."RoleID", p."PermissionID"
FROM "Role" r, "Permission" p
WHERE r."RoleName" = 'DirectorOfAdministration' AND p."PermissionKey" IN ('estimate.generateFCN', 'estimate.verifyFCN')
ON CONFLICT DO NOTHING;

-- Remove FCN permissions from Finance Head (Finance Head owns Approval + Cheque, not FCN)
DELETE FROM "RolePermission" rp
USING "Role" r, "Permission" p
WHERE rp."RoleID" = r."RoleID" AND rp."PermissionID" = p."PermissionID"
  AND r."RoleName" = 'FinanceHead' AND p."PermissionKey" IN ('estimate.generateFCN', 'estimate.verifyFCN');

-- FCN number is now authoritative from FCN_Seq — prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS "FCN_FCNNo_unique" ON "FCN"("FCNNo");
