import { useState, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { ArrowLeft, Printer, Loader2, FileText } from 'lucide-react'
import api from '../utils/api'
import toast from 'react-hot-toast'
import StatusBadge from '../components/shared/StatusBadge'
import LOADocument from '../components/print/LOADocument'

const fmtDate = (d) => (d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—')
const fmtDateTime = (d) => (d ? new Date(d).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : '—')

export default function LoaDetail() {
  const { tenderId } = useParams()
  const navigate = useNavigate()
  const [loa, setLoa] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)

  useEffect(() => { load(); /* eslint-disable-next-line */ }, [tenderId])

  const load = async () => {
    setLoading(true)
    setError(null)
    try {
      setLoa((await api.get(`/loa/tender/${tenderId}`)).data)
    } catch (err) {
      setError(err.response?.data?.error || 'Letter of Award could not be loaded')
    } finally { setLoading(false) }
  }

  const openPrint = () => {
    setBusy(true)
    try {
      api.post(`/loa/tender/${tenderId}/print`).then(() => load()).catch(() => {})
      window.open(`/print/loa/${tenderId}`, '_blank')
    } finally { setBusy(false) }
  }

  if (loading) return <div className="p-6 text-sm text-slate-400">Loading…</div>

  if (error || !loa) {
    return (
      <div className="p-6 max-w-md mx-auto text-center space-y-3">
        <p className="text-sm font-medium text-[#0F172A]">{error || 'No Letter of Award for this tender'}</p>
        <p className="text-xs text-slate-400">Tender: #{tenderId}</p>
        <div className="flex items-center justify-center gap-2">
          <button onClick={load} className="ec-btn-sm ec-btn-primary">Retry</button>
          <Link to={`/tenders/${tenderId}`} className="ec-btn-sm ec-btn-ghost">Back to Tender</Link>
        </div>
      </div>
    )
  }

  const info = [
    ['LOA Number', loa.LOANumber],
    ['Tender Number', loa.TenderNo],
    ['Status', <StatusBadge status={loa.Status} key="s" />],
    ['Document Status Note', loa.Status === 'Generated' ? 'Not yet printed' : `Printed on ${fmtDateTime(loa.PrintedAt)}`],
    ['Awarded Agency', loa.ContractorName || '—'],
    ['Award Amount', `Rs. ${Number(loa.AwardAmount || 0).toLocaleString('en-IN')}`],
    ['Award Date', fmtDate(loa.AwardedAt)],
    ['Location', loa.locationLine || '—'],
    ['Generated By', `${loa.GeneratedByName || '—'} (${fmtDateTime(loa.GeneratedAt)})`],
  ]

  return (
    <div className="min-w-0 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate(`/tenders/${tenderId}`)} className="p-1.5 rounded text-[#475569] hover:bg-[#F1F5F9]"><ArrowLeft className="w-4 h-4" /></button>
          <div>
            <h1 className="ec-page-title">{loa.LOANumber}</h1>
            <p className="ec-page-subtitle">{loa.NameOfWork}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={openPrint} disabled={busy} className="ec-btn-sm ec-btn-primary">
            {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Printer className="w-3.5 h-3.5" />}
            Print / Download PDF
          </button>
          <Link to={`/tenders/${tenderId}`} className="ec-btn-sm ec-btn-ghost">Back to Tender</Link>
        </div>
      </div>

      <div className="ec-card overflow-hidden">
        <div className="ec-card-header flex items-center justify-between">
          <span className="ec-card-title"><FileText className="w-4 h-4 inline mr-1" /> Letter of Award</span>
          <StatusBadge status={loa.Status} />
        </div>
        <div className="ec-card-body grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
          {info.map(([k, v]) => (
            <div key={k}><p className="text-[10px] uppercase tracking-wide text-slate-400">{k}</p><p className="font-medium break-words">{typeof v === 'string' ? (v || '—') : v}</p></div>
          ))}
        </div>
        {loa.Conditions && (
          <div className="ec-card-body border-t text-xs">
            <p className="text-[10px] uppercase tracking-wide text-slate-400 mb-1">Conditions / Terms</p>
            <pre className="whitespace-pre-wrap font-sans text-xs leading-relaxed">{loa.Conditions}</pre>
          </div>
        )}
      </div>

      <div className="print-wrapper">
        <LOADocument loa={loa} />
      </div>
    </div>
  )
}