const express = require('express');
const router = express.Router();
const workflowController = require('../controllers/workflowController');
const deletedEstimateController = require('../controllers/deletedEstimateController');
const { authenticate } = require('../middleware/auth');
const { requireRole } = require('../middleware/rbac');

router.post('/:id/submit/request-otp', authenticate, workflowController.requestSubmitOtp);
router.post('/:id/submit', authenticate, workflowController.submitEstimate);
router.post('/:id/revert', authenticate, workflowController.revertEstimate);
router.post('/:id/approve/request-otp', authenticate, workflowController.requestDgmApproveOtp);
router.post('/:id/approve', authenticate, workflowController.verifyDgmApprove);
router.post('/:id/sign/request-otp', authenticate, workflowController.requestSignatureOtp);
router.post('/:id/sign', authenticate, workflowController.signAndAuditEstimate);
router.post('/:id/cgm-submit/request-otp', authenticate, workflowController.requestCgmSubmitOtp);
router.post('/:id/cgm-submit', authenticate, workflowController.verifyCgmSubmit);
router.post('/:id/dop-approve/request-otp', authenticate, workflowController.requestDopApproveOtp);
router.post('/:id/dop-approve', authenticate, workflowController.verifyDopApprove);
router.post('/:id/ed-approve/request-otp', authenticate, workflowController.requestEdApproveOtp);
router.post('/:id/ed-approve', authenticate, workflowController.verifyEdApprove);
router.post('/:id/md-final/request-otp', authenticate, workflowController.requestMdFinalOtp);
router.post('/:id/md-final', authenticate, workflowController.verifyMdFinal);
router.post('/:id/delete/request-otp', authenticate, deletedEstimateController.requestDeleteOtp);
router.post('/:id/delete', authenticate, deletedEstimateController.verifyDelete);
router.post('/:id/publish-tender', authenticate, workflowController.publishTender);
router.post('/:id/select-agency', authenticate, workflowController.selectAgency);
router.post('/:id/start-work', authenticate, workflowController.startWork);
router.post('/:id/complete-work', authenticate, workflowController.completeWork);
router.post('/:id/submit-bill', authenticate, workflowController.submitBill);
router.post('/:id/archive', authenticate, workflowController.archiveComplete);
router.post('/:id/generate-fcn', authenticate, workflowController.generateFCN);
router.post('/:id/generate-admin-sanction', authenticate, workflowController.generateAdminSanction);
router.post('/:id/assign-ts-authority', authenticate, workflowController.assignTsAuthority);
router.post('/:id/approve-ts', authenticate, workflowController.approveTs);
router.post('/:id/return-ts', authenticate, workflowController.returnTs);
router.post('/:id/review-forward-gm', authenticate, workflowController.reviewForwardGm);
router.post('/:id/review-forward-dgm', authenticate, workflowController.reviewForwardDgm);
router.post('/:id/close-tender', authenticate, requireRole('TenderOfficer'), workflowController.closeTender);
router.post('/:id/technical-eval', authenticate, requireRole('DirectorOfAdministration'), workflowController.technicalEval);
router.post('/:id/financial-eval', authenticate, requireRole('DirectorOfAdministration'), workflowController.financialEval);
router.post('/:id/identify-l1', authenticate, requireRole('DirectorOfAdministration'), workflowController.identifyL1);
router.post('/:id/create-award', authenticate, requireRole('DirectorOfAdministration'), workflowController.createAward);
router.post('/:id/issue-work-order', authenticate, requireRole('DirectorOfAdministration'), workflowController.issueWorkOrder);
router.post('/:id/record-agreement', authenticate, requireRole('DirectorOfAdministration'), workflowController.recordAgreement);
router.post('/:id/return-to-fcn', authenticate, workflowController.returnToFCN);
router.post('/:id/return-to-director', authenticate, workflowController.returnToDirector);
router.post('/:id/return-to-gm', authenticate, workflowController.returnToGM);
router.post('/:id/return-to-dgm', authenticate, workflowController.returnToDGM);
router.get('/:id/history', authenticate, workflowController.getWorkflow);
router.get('/pending', authenticate, workflowController.getPendingApprovals);

module.exports = router;
